#!/bin/bash -login

#PBS -l walltime=72:00:00,nodes=1:ppn=8,mem=168gb
#PBS -N dn_occ_oases_c10
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer
module load oases
module load velvet

WKDR='/mnt/scratch/loweelij/mol_paper/dn_occ_oases_c10/'

mkdir $WKDR
cd $WKDR
ln -fs /mnt/scratch/loweelij/mol_paper/mocc_reads/* .
normalize-by-median.py -p -C 10 -k 20 -N 4 -x 4e9 -s mocc_tr_normC20k20.kh *pe
wait
normalize-by-median.py -C 10 -k 20 -l mocc_tr_normC20K20.kh *se
wait
paired=*pe.keep
single=*se.keep
velveth ${WKDR}output 21,35,2 -fastq -shortPaired $paired -short $single
wait
for((n=21;n<35;n=n+2));do velvetg ${WKDR}output_"$n" -cov_cutoff auto -exp_cov auto -read_trkg yes -scaffolding no -ins_length 250; done
wait
for((n=21;n<35;n=n+2));do oases ${WKDR}output_"$n"; done

qstat -f ${PBS_JOBID}

