#!/bin/bash -login

#PBS -l walltime=72:00:00,nodes=1:ppn=8,mem=32gb
#PBS -N dn_ocu_tri
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer
module load bowtie
module load trinity

WKDR='/mnt/scratch/loweelij/mol_paper/dn_ocu_tri/'
mkdir $WKDR
cd $WKDR
ln -fs /mnt/scratch/loweelij/mol_paper/mocu_reads/* .
normalize-by-median.py -p -C 20 -k 20 -N 4 -x 2e9 --savehash mocu_tr_normC20k20.kh *pe
wait
normalize-by-median.py -C 20 -k 20 -N 4 -x 2e9 --loadhash mocu_tr_normC20K20.kh *se
wait
for i in *pe.keep; do split-paired-reads.py $i;done
wait
cat *.1 > left.fq
cat *.2 > right.fq
wait
cat *.se.keep >> left.fq
wait
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 16G

qstat -f ${PBS_JOBID}

