#!/bin/bash -login

#PBS -l walltime=24:00:00,nodes=1:ppn=8,mem=168gb
#PBS -N dn_ocu_oases
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer
module load oases
module load velvet

WKDR='/mnt/scratch/loweelij/mol_paper/dn_ocu_oases/'
mkdir $WKDR
cd $WKDR
ln -fs /mnt/scratch/loweelij/mol_paper/mocu_reads/* .
python /mnt/home/loweelij/khmer/scripts/normalize-by-median.py -p -C 20 -k 20 -N 4 -x 2e9 --savehash mocu_tr_normC20k20.kh *pe
wait
python /mnt/home/loweelij/khmer/scripts/normalize-by-median.py -C 20 -k 20 -N 4 -x 2e9 --loadhash mocu_tr_normC20K20.kh *se
wait
velveth ${WKDR}output 21,35,2 -fastq -shortPaired SRR1197522.fastq.pe.qc.fq.pe.keep SRR1197965.fastq.pe.qc.fq.pe.keep SRR1197972.fastq.pe.qc.fq.pe.keep -short SRR1197522.fastq.pe.qc.fq.se.keep SRR1197965.fastq.pe.qc.fq.se.keep SRR1197972.fastq.pe.qc.fq.se.keep
wait
for((n=21;n<35;n=n+2));do velvetg ${WKDR}output_"$n" -cov_cutoff auto -exp_cov auto -read_trkg yes -scaffolding no -ins_length 250; done
wait
for((n=21;n<35;n=n+2));do oases ${WKDR}output_"$n"; done

qstat -f ${PBS_JOBID}

