#!/bin/bash -login

#PBS -l walltime=168:00:00,nodes=1:ppn=8,mem=350gb
#PBS -N raw_occ_oases
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer
module load oases
module load velvet

WKDR='/mnt/scratch/loweelij/mol_paper/raw_occ_oases/'
mkdir $WKDR
cd $WKDR
ln -fs /mnt/scratch/loweelij/mol_paper/mocc_reads/* .
velveth ${WKDR}output 21,35,2 -fastq -shortPaired SRR1197985.fastq.pe.qc.fq.pe SRR1197986.fastq.pe.qc.fq.pe SRR1199464.fastq.pe.qc.fq.pe SRR1199259.fastq.pe.qc.fq.pe SRR1199268.fastq.pe.qc.fq.pe -short SRR1197985.fastq.pe.qc.fq.se SRR1197986.fastq.pe.qc.fq.se SRR1199464.fastq.pe.qc.fq.se SRR1199259.fastq.pe.qc.fq.se SRR1199268.fastq.pe.qc.fq.se
wait
for((n=21;n<35;n=n+2));do velvetg ${WKDR}output_"$n" -cov_cutoff auto -exp_cov auto -read_trkg yes -scaffolding no -ins_length 250; done
wait
for((n=21;n<35;n=n+2));do oases ${WKDR}output_"$n"; done

qstat -f ${PBS_JOBID}

