#!/bin/bash -login

#PBS -l walltime=48:00:00,nodes=1:ppn=8,mem=32gb
#PBS -N raw_ocu_tri
#PBS -A ged-intel11
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load screed
module load khmer
module load bowtie
module load trinity

mkdir /mnt/scratch/loweelij/mol_paper/raw_ocu_tri/
cd /mnt/scratch/loweelij/mol_paper/raw_ocu_tri/
ln -fs /mnt/scratch/loweelij/mol_paper/mocu_reads/* .
for i in *pe; do split-paired-reads.py $i;done
wait
cat *.1 > left.fq
cat *.2 > right.fq
wait
cat *.se >> left.fq
wait
Trinity.pl --left left.fq --right right.fq --seqType fq -JM 16G

qstat -f ${PBS_JOBID}

